title: Forez Transition & Climat
description: Accompagnement local pour la transition écologique dans le Forez.
baseurl: "" # laisser vide pour GitHub Pages à la racine
url: "https://forez-transition.fr" # ton domaine final
theme: null
markdown: kramdown
permalink: pretty
paginate: 5
